# Parse OVMF log file, replacing GUIDs with their name, using the xref file
# Guid.xref, generated by the EDK2 build system

BEGIN {
	if (length(guidxref) == 0) {
		print "Usage: awk -f guidlookup.awk -v guidxref=<guidxref filename> [logfile]"
		exit	
	}
	guidregex = "[a-fA-F0-9]{8}-([a-fA-F0-9]{4}-){3}[a-fA-F0-9]{12}"
	print "Reading guid xref data from " guidxref
	while ((getline line < guidxref) > 0)
	{
		gsub(/\r/,"",line)
#		print line
		split(line, f, " ")
#		print "f1=" f[1] ",f2=" f[2]
		guidname[f[1]]=f[2]
	}
	close(guidxref)
}

{
	line = $0
	if (pos = match(line, guidregex, guidarr)) {
		gsub(guidregex, "(" guidname[guidarr[0]] ")", line)
	}
	print line
}

END {
}
